### ISSUE TITLE
Error : java.lang.IllegalStateException: Module entity with name: wonderous_compose should be available

### ISSUE THREAD

**Issue by jeffnyauke** [ShreyashKore/wonderous_compose#1]
Error when syncing the project

**Comment by ShreyashKore** [comment]
Hello @jeffnyauke, I'm unable to reproduce this error on my freshly cloned repo. Can you provide detailed error logs?

**Comment by jeffnyauke** [comment]
Hmm.. looks like it's a bug in Android Studio Iguana 2023.2.1 Canary 18. Opened the project in the stable version and it was okay!
