### ISSUE TITLE
Map controls and contributors link at wrong position

### ISSUE THREAD

**Issue by twissmueller** [ShreyashKore/wonderous_compose#25]
Using parts of your code to integrate openlayers in my Compose Web application for displaying a full screen map.

I have noticed that the control buttons and the link for the contributors are all cramped up in the top left corner of the map. This is also in the online example of Wonderous Compose, please see screenshot.

<img width="611" alt="image" src="https://github.com/user-attachments/assets/fcd5d6e3-a58a-48f3-9a27-7342e93919b0">

Any idea how to place the controls somewhere else, e.g. on the bottom?

**Comment by ShreyashKore** [comment]
You will need to include the CSS in the OpenLayers Map file for the controls and attributions to look better. Default placement is, the controls at top-left and attributions at bottom-right. For including CSS you can try following this [article](https://touchlab.co/compose-html-style-libraries) (Including the CSS in index.html file should also work). For custom positioning you need to write your own CSS as [this](https://stackoverflow.com/questions/20981679/openlayers-map-change-position-of-attribution-in-javascript) StackOverflow answer suggests.

**Comment by twissmueller** [comment]
Thanks a lot @ShreyashKore, this is what I have added to my `styles.css` and exactly how I wanted it:

```
.ol-attribution {
    display: none;
}

.ol-rotate {
    display: none;
}

.ol-zoom {
    position: fixed;
    bottom: 10px;
    right: 10px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
}

.ol-zoom button {
    width: 50px;
    height: 50px;
    font-size: 24px;
}
```

And this is the result:
![Uploading image.png…]()

**Comment by ShreyashKore** [comment]
fixed
